force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Hold the invoice data just to show you how the things will work</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BitcoinPrice__c.field-meta.xml
<CustomField>
    <fullName>BitcoinPrice__c</fullName>
    <label>Bitcoin Price</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/tests/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static void makeSingleData(){
        Account objAccount = new Account(
            Name = 'Testing ' + generateRandomString(10)
        );

        insert objAccount;

        Contact objContact = new Contact(
            AccountId = objAccount.id,
            FirstName = 'Test' + generateRandomString(10),
            LastName = 'Contact'

        );

        insert objContact;

        Invoice__c objInvoice = new Invoice__c(
            ContactId__c = objContact.Id,
            BitcoinPrice__c = 0,
            ExpirationDate__c = System.today(),
            Price__c = 1000
        );

        insert objInvoice;

    }

    public static void makeBatchData(){
        Account objAccount = new Account(
            Name = 'Testing ' + generateRandomString(10)
        );

        insert objAccount;

        Contact objContact = new Contact(
            AccountId = objAccount.id,
            FirstName = 'Test' + generateRandomString(10),
            LastName = 'Contact'

        );

        insert objContact;

        List<Invoice__c> lstInvoice = new List<Invoice__c>();

        // Inserts 101 rows
        for (Integer i=0;i<10;i++) {
            lstInvoice.add(
                new Invoice__c (
                    ContactId__c = objContact.Id,
                    BitcoinPrice__c = 0,
                    ExpirationDate__c = System.today(),
                    Price__c = 1000 + i
                )
            );
        }

        // Create an expired one
        lstInvoice.add(
            new Invoice__c (
                ContactId__c = objContact.Id,
                BitcoinPrice__c = 0,
                ExpirationDate__c = System.today() - 5,
                Price__c = 5000000
            )
        );


        insert lstInvoice;
    }

    public static String generateRandomString(Integer lengthOfString) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < lengthOfString) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}