force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Hold the invoice data just to show you how the things will work</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BitcoinPrice__c.field-meta.xml
<CustomField>
    <fullName>BitcoinPrice__c</fullName>
    <label>Bitcoin Price</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/InvoiceScheduleTest.cls
@IsTest
private class InvoiceScheduleTest {
    public static String execTime = '0 0 8 1/1 * ? *';

    @TestSetup
    static void makeData(){
        TestDataFactory.makeBatchData();
    }

    @IsTest
    static void testScheduledJob() {
        Test.setMock(HttpCalloutMock.class, new InvoiceMockUpTest()); 
        
        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest', execTime, new InvoiceSchedule());
        Test.stopTest();
        Decimal bitcoinValue = [
            SELECT Id, BitcoinPrice__c
            FROM Invoice__c
            WHERE BitcoinPrice__c > 0
            LIMIT 1
        ]?.BitcoinPrice__c;

        Assert.areNotEqual(0, bitcoinValue);
        Assert.areNotEqual('', jobId);
    }
}