force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Hold the invoice data just to show you how the things will work</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BitcoinPrice__c.field-meta.xml
<CustomField>
    <fullName>BitcoinPrice__c</fullName>
    <label>Bitcoin Price</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/InvoiceControllerTest.cls
@isTest
global class InvoiceControllerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.makeSingleData();
    }


    @isTest static void setBitcoinValueTest(){
        Test.setMock(HttpCalloutMock.class, new InvoiceMockUpTest()); 
        String invoiceId = String.valueOf([
            SELECT Id
            FROM Invoice__c
            LIMIT 1
        ]?.Id);

        Test.startTest();
        InvoiceController.setBitcoinValue(invoiceId);
        Test.stopTest();
        Decimal bitcoinValue = [
            SELECT Id, BitcoinPrice__c
            FROM Invoice__c
            WHERE Id =:invoiceId
            LIMIT 1
        ]?.BitcoinPrice__c;

        InvoiceHelper.bpi objIns = new InvoiceHelper.bpi();

        Assert.areNotEqual(0, bitcoinValue);
    }
}