force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Hold the invoice data just to show you how the things will work</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BitcoinPrice__c.field-meta.xml
<CustomField>
    <fullName>BitcoinPrice__c</fullName>
    <label>Bitcoin Price</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/InvoiceBatchTest.cls
@isTest
global class InvoiceBatchTest{
    @TestSetup
    static void makeData(){
        TestDataFactory.makeBatchData();
    }

    @isTest static void batchTest() {        
        Test.setMock(HttpCalloutMock.class, new InvoiceMockUpTest()); 

        Test.startTest();
        InvoiceBatch objBatch = new InvoiceBatch();
        Id batchId = Database.executeBatch(objBatch);
        Test.stopTest();
        // after the testing stops, assert records were updated properly

        Decimal bitcoinValue = [
            SELECT Id, BitcoinPrice__c
            FROM Invoice__c
            WHERE BitcoinPrice__c > 0
            LIMIT 1
        ]?.BitcoinPrice__c;

        InvoiceHelper.bpi objIns = new InvoiceHelper.bpi();

        Assert.areNotEqual(0, bitcoinValue);

    }
}