force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Hold the invoice data just to show you how the things will work</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batches/InvoiceBatch.cls
global class InvoiceBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    
    // Total de registros processados
    global Integer intTotalRegistros = 0;
    global Decimal bitcoinValue = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String queryData = 'SELECT Id, ExpirationDate__c ';
        queryData += 'FROM Invoice__c ';
        queryData += 'WHERE Status__c = \'Open\'';
        
        return Database.getQueryLocator(queryData);
    }
    global void execute(Database.BatchableContext bc, List<Invoice__c> scope){
        Set<String> expiredId = new Set<String>();
        Set<String> updateId = new Set<String>();
        Date todayDate = Date.today();

        if (bitcoinValue ==0) bitcoinValue = InvoiceHelper.getDecimalBitcoinValue();

        for (Invoice__c rowData : scope) {
            if (rowData.ExpirationDate__c < todayDate){
                // system.debug('Expired ');
                expiredId.add(rowData.Id);
            } else {
                // system.debug('Update');
                updateId.add(rowData.Id);
            }        
        }

        intTotalRegistros += expiredId.size() + updateId.size();
        // Update the records
        if (updateId.size()>0 || expiredId.size()>0 ) InvoiceHelper.setBitcoinValues(updateId, expiredId, bitcoinValue);

    }    
    global void finish(Database.BatchableContext bc){
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        // call some utility to send email
        //EmailUtils.sendMessage(job, intTotalRegistros);
        System.debug('Total records processed: ' + intTotalRegistros + ' job information ' + job);
    }    
}